<div class="container">
    <div class="header"><?= $this->translate->_("Aircrafts list") ?></div>
    <table>
        <tr>
            <th><?= $this->translate->_("Name") ?></th>
            <th><?= $this->translate->_("Type") ?></th>
        </tr>
        <?php foreach($this->aircrafts as $aircraft): ?>
            <tr>
                <td><?= $aircraft['name'] ?></td>
                <td><?= $aircraft['AircraftType']['type'] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>