<table class="table-pane">
    <tr>
        <th><?= $this->translate->_("Name") ?></th>
        <th><?= $this->translate->_("Type") ?></th>
        <th><?= $this->translate->_("Status") ?></th>
    </tr>
    <?php foreach($this->aircrafts as $aircraft): ?>
        <tr>
            <td><?= $aircraft['name'] ?></td>
            <td><?= $this->translate->_($aircraft['AircraftType']['type']) ?></td>
            <td><?= $this->translate->_($aircraft['AircraftStatus']['status']) ?></td>
        </tr>
    <?php endforeach; ?>
</table>