<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8') ?>

        <?php $this->headLink()->appendStylesheet($this->baseUrl("/css/default.css")) ?>
        <?php $this->JQuery()->setLocalPath($this->baseUrl("/js/jquery-1.4.2.min.js")) ?>
        <?php $this->JQuery()->addStylesheet($this->baseUrl("/css/custom-theme/jquery-ui-1.8.2.custom.css")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/jquery-ui-1.8.2.custom.min.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/jquery.layout.min-1.2.0.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/jquery.pnotify.min.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/application.js")) ?>

        <?php $this->JQuery()->addOnLoad("myLayout = applyLayout(); navigationPanels();") ?>
        <?php $this->JQuery()->addOnLoad("consumeAlert('".$this->translate->_('Message')."');") ?>
        <?php if($this->acl()->isValid("user", "messages")): ?>
            <?php $this->JQuery()->addOnLoad("getMessages('".$this->baseUrl("/user/messages/format/json")."');") ?>
        <?php endif; ?>
        <script type="text/javascript">
            var myLayout;
            var _alert;
        </script>

        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
        <?php echo $this->JQuery() ?>

    </head>
    <body>
        <div class="ui-layout-north" class="header">
            <h1><?= $this->app['header'] ?></h1>
            <?= $this->login() ?>
            <div id="calNav">
                <?= $this->toolbar()->render();?>
            </div>
        </div>
        <div class="ui-layout-west">
            <div class="side-pane">
                <h1><?= $this->translate->_("Navigation") ?></h1>
                <?= $this->navigation()->menu()->setMaxDepth(0) ?>
            </div>
            <div class="side-pane">
                <h1><?= $this->translate->_("Messages") ?></h1>
                <ul>
                    <li><?= $this->translate->_("Unread") ?> <span class="counter" id="msg-counter">0</span></li>
                </ul>
            </div>
        </div>
        <div class="ui-layout-center">
            <?= $this->layout()->content ?>
        </div>
        <div class="ui-layout-south">
            <span class="align-left">Version <?= $this->app['version'] ?></span>
            <span class="align-right"><?= ucfirst($this->app['environment']) ?> Environment</span><br>
            <?php if($this->app['environment'] == 'development'): ?>
                <span class="align-left">Zend Framework Version: <?= Zend_Version::VERSION ?></span><br>
                <span class="align-left">Doctrine Version: <?= Doctrine_Core::VERSION ?></span><br>
            <?php endif; ?>
        </div>
    </body>
</html>
