<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8') ?>

        <?php $this->headLink()->appendStylesheet($this->baseUrl("/css/default.css")) ?>
        
        <?php $this->JQuery()->setLocalPath($this->baseUrl("/js/jquery-1.4.2.min.js")) ?>
        <?php $this->JQuery()->addStylesheet($this->baseUrl("/css/smoothness/jquery-ui-1.8.custom.css")) ?>
        <?php $this->JQuery()->setUILocalPath($this->baseUrl("/js/jquery-ui-1.8.custom.min.js")) ?>
        <?php $this->JQuery()->addStylesheet($this->baseUrl("/css/fullcalendar.css")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/fullcalendar.min.js")) ?>

        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
        <?= $this->JQuery() ?>
    </head>
    <body>
        <div class="header">
            <h1><?= $this->app['header'] ?></h1>
            <?= $this->login() ?>
        </div>
        <div class="messages">
            <?= $this->messages() ?>
            <?php if($this->messages): ?>
                <ul>
                <?php foreach($this->messages as $message):?>
                    <li><?= $message ?></li>    
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
        <?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
        <div class="menu">
            <?= $this->navigation()->menu()->setMaxDepth(0) ?>
        </div>
        <?php endif; ?>
        <div class="content">
            <div class="breadcrumbs">
                <?= $this->navigation()->breadcrumbs()->setMinDepth(1) ?>
            </div>
            <?= $this->layout()->content ?>
        </div>
        <div class="footer">
            <span class="align-left">Version <?= $this->app['version'] ?></span>
            <span class="align-right"><?= ucfirst($this->app['environment']) ?> Environment</span><br>
            <?php if($this->app['environment'] == 'development'): ?>
                <span class="align-left">Zend Framework Version: <?= Zend_Version::VERSION ?></span><br>
                <span class="align-left">Doctrine Version: <?= Doctrine_Core::VERSION ?></span><br>
            <?php endif; ?>
        </div>
    </body>
</html>
