<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8') ?>

        <?php $this->headLink()->appendStylesheet($this->baseUrl("/css/default.css")) ?>
        <?php $this->JQuery()->setLocalPath($this->baseUrl("/js/jquery-1.4.2.min.js")) ?>
        <?php $this->JQuery()->addStylesheet($this->baseUrl("/css/smoothness/jquery-ui-1.8.1.custom.css")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/jquery-ui-1.7.3.custom.min.js")) ?>
        <?php $this->JQuery()->addStylesheet($this->baseUrl("/css/fullcalendar.css")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/fullcalendar.min.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/jquery.layout.min-1.2.0.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/jquery.custom.js")) ?>

        <?php $this->JQuery()->addOnLoad("var myLayout = applyLayout(); navigationPanels();") ?>

        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
        <?= $this->JQuery() ?>

    </head>
    <body>
        <div class="ui-layout-north" class="header">
            <h1><?= $this->app['header'] ?></h1>
            <?= $this->login() ?>
             <div class="messages">
                <?= $this->messages() ?>
                <?php if($this->messages): ?>
                    <ul>
                        <?php foreach($this->messages as $message):?>
                            <li><?= $message ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
        <div class="ui-layout-west">
            <div class="side-pane">
                <h1><?= $this->translate->_("Navigation") ?></h1>
                <?= $this->navigation()->menu()->setMaxDepth(0) ?>
            </div>
            <div class="side-pane">
                <h1><?= $this->translate->_("Messages") ?></h1>
                <ul>
                    <li><?= $this->translate->_("Unread") ?> <span class="counter">0</span></li>
                </ul>
            </div>
        </div>
        <div class="ui-layout-center">
            <?= $this->layout()->content ?>
        </div>
        <div class="ui-layout-south">
            <span class="align-left">Version <?= $this->app['version'] ?></span>
            <span class="align-right"><?= ucfirst($this->app['environment']) ?> Environment</span><br>
            <?php if($this->app['environment'] == 'development'): ?>
                <span class="align-left">Zend Framework Version: <?= Zend_Version::VERSION ?></span><br>
                <span class="align-left">Doctrine Version: <?= Doctrine_Core::VERSION ?></span><br>
            <?php endif; ?>
        </div>
    </body>
</html>
