<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8') ?>

        <?php $this->headLink()->appendStylesheet($this->baseUrl("/css/default.css")) ?>
        <?php $this->JQuery()->setLocalPath($this->baseUrl("/js/jquery-1.4.2.min.js")) ?>
        <?php $this->JQuery()->addStylesheet($this->baseUrl("/css/custom-theme/jquery-ui-1.8.4.custom.css")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/jquery-ui-1.8.4.custom.min.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/jquery.layout.min-1.2.0.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/jquery.label.js")) ?>
        <?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/application.js")) ?>

        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
        <?= $this->JQuery() ?>

        <?= $this->JQuery()->addOnLoad("applyLayout();") ?>
    </head>
<script type="text/javascript">
$(document).ready(function() {
    $("#loginForm label").overlabel();
});
</script>
    <body id="loginPage">
        <div class="ui-layout-center">
            <div id="loginForm">
                <div id="loginLogo">AENSA</div>
            <?php if($this->messages): ?>
                <div id="loginMessage">
                    <?php foreach($this->messages as $message):?>
                        <p><?= $message ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
                <?= $this->layout()->content ?>
            </div>
        </div>
    </body>
</html>