<?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/wdCalendar_lang_US.js")) ?>
<?php $this->JQuery()->addJavascriptFile($this->baseUrl("/js/plugins/jquery.calendar.js")) ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl("/css/calendar.css")) ?>
<script type="text/javascript">
    function quickAdd(start, end, isAllDay, pos, render)
    {
        modalDialog(
            '<?= $this->baseUrl ?>/index/reserve/format/json',
            {
                'startDate': formatDate(start),
                'endDate': formatDate(end),
                'isAllDay':isAllDay
            },
            [render]);
    }
</script>
<?= $this->jqCalendar("mainCalendar", $this->jqCalendar, array('quickAddCallback' => 'quickAdd')) ?>
<? $this->toolbar()
        ->addOnLoad()
        ->addButton("day-btn", $this->translate->_("Day"), array('onclick' => "changeCalendarView('mainCalendar', $(this), 'day');"))
        ->addButton("week-btn", $this->translate->_("Week"), array('onclick' => "changeCalendarView('mainCalendar', $(this), 'week');", 'checked' => "checked"))
        ->addButton("month-btn", $this->translate->_("Month"), array('onclick' => "changeCalendarView('mainCalendar', $(this), 'month');")) ?>
