<?php

/**
 * Model_Base_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $first_name
 * @property varchar $last_name
 * @property varchar $username
 * @property varchar $password
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_User extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('first_name', 'varchar', 200, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('last_name', 'varchar', 200, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('username', 'varchar', 200, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('password', 'varchar', 200, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '200',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}