<?php if($this->acl()->isValid("aircraft", "create")): ?>
    <?php $this->toolbar()
            ->addOnLoad()
            ->setButtonset(false)
            ->addButton("create-btn", $this->translate->_("Delete all"), array('onclick' => "alert('Not implemented')"))?>
<?php endif; ?>

<?php if (empty($this->data)): ?>
	<div class="no-data"><?= $this->translate->_("There's no messages") ?></div>
<?php else:?>
	<table class="table-pane" id="main-table">
	    <thead>
	    	<tr>
	    		<th style="width: 30px"></th>
	    		<th><?= $this->translate->_("Message") ?></th>
	    		<th><?= $this->translate->_("From") ?></th>
	    		<th><?= $this->translate->_("Date")?></th>
	        </tr>
	    </thead>
	    <?php foreach($this->data as $row): ?>
	        <tr>
	        	<td>
	        		<?php if(!$row['is_read']):?>
	        			<a href="<?= $this->baseUrl("/message/index/subaction/read/id/".$row['id']) ?>" title="<?= $this->translate->_("Mark as a read") ?>"><span class="unread-icon">&nbsp;</span></a>
	        		<?php endif; ?>
	        	</td>
	        	<td class="align-left">
	        		<?php 
	        			$isRead = !$row['is_read'] ? 'class="bold"' : '';
	        		?>
	        		<span <?= $isRead ?>><?= $row['subject']?></span><br>
	        		<span style="color: #888;"><?= $row['content']?></span>
	        	</td>
	        	<td>
	        		<?= $row['FromUser']['first_name']?> 
	        		<?= $row['FromUser']['last_name']?>
	        	</td>
	        	<td><?= $row['created_on'] ?></td>
	        </tr>
	    <?php endforeach; ?>
	</table>
<?php endif; ?>