<?php

$data = array(
    "showEdit" => array(
        'controller' => "acl",
        'action'     => "edit_role"
    ),
    'headerNames' => array(
        "Id", "Role", "Description", "Permissions"
    ),
    'data' => $this->roles,
    'columns' => array(
        array("name" => "id"),
        array("name" => "name"),
        array("name" => "description"),
        array (
            'helper' => 'showRolePermissions',
            'name'   => 'AclPermission'
        )
    )
);

echo $this->partial("partials/table.phtml", $data);

?>


<?php if($this->acl()->isValid("acl", "create_role")): ?>
    <?php $this->toolbar()
            ->addOnLoad()
            ->setButtonset(false)
            ->addButton("create-btn", $this->translate->_("Create Role"), array('onclick' => "modalDialog('".$this->baseUrl."/acl/create_role/format/json');"))?>
<?php endif; ?>