<?php

/**
 * AclPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AclPermission extends BaseAclPermission
{

    public static function findAll()
    {
        return Doctrine_Query::create()
                    ->from("AclPermission ap")
                    ->leftJoin("ap.AclResource ar")
                    ->leftJoin("ap.AclRole aro")
                    ->fetchArray();
    }

    /**
     * Delete one+ permissions from a role
     * @param int $roleId
     * @param array $permissions
     * @return int
     */
    public static function deleteRolePermissions($roleId, $permissions)
    {
        if (!empty($permissions) && !empty($roleId))
        {
            $class = __CLASS__;
            $r = Doctrine_Query::create()
                        ->delete("$class p")
                        ->addWhere("p.role_id = $roleId")
                        ->addWhere("p.resource_id in (".implode(",", $permissions).")")
                        ->execute();

            return $r;
        }
        return false;
    }

}