<?php

/**
 * AclRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AclRole extends BaseAclRole
{
    public static function findAll()
    {
        return Doctrine_Query::create()
                    ->from("AclRole r")
                    ->leftJoin('r.AclPermission p')
                    ->leftJoin('p.AclResource re')
                    ->fetchArray();

    }
    
    public static function create($params)
    {
        $aclRole = new AclRole();
        $aclRole->name = $params['name'];
        $aclRole->description = $params['description'];
        $aclRole->save();
        $aclRole->refresh();
        
        if (!empty($params['resources']))
        {
            $resources = is_array($params['resources']) ? $params['resources'] : array($params['resources']);
            foreach($resources as $resource)
            {
                $permission = new AclPermission();
                $permission->resource_id = $resource;
                $permission->role_id = $aclRole->id;
                $permission->save();
            }            
        }
        
        return $aclRole->id;
    }
}