<?php

/**
 * Aircraft
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Aircraft extends BaseAircraft
{

    /**
     * Get all aircraft with his types
     * @return array
     */
    public static function findAll()
    {
        return Doctrine_Query::create()
                    ->from("Aircraft a")
                    ->leftJoin("a.AircraftType t")
                    ->leftJoin("a.AircraftStatus s")
                    ->fetchArray(true);
    }
    
    public function create($params)
    {
        if(!empty($params))
        {
            $aircraft = new Aircraft();
            $aircraft->name = $params['name'];
            $aircraft->type_id = $params['type_id'];
            $aircraft->status_id = $params['status_id'];
            $aircraft->save();
            $aircraft->refresh();
            
            return $aircraft->id;
        }
        
        return false;
    }

}