<?php

/**
 * Messages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Messages extends BaseMessages
{

    public static function findUnreadByUserId($userId)
    {
        return Doctrine_Query::create()
                    ->from("Messages m")
                    ->leftJoin("m.FromUser fu")
                    ->leftJoin("m.ToUser tu")
                    ->addWhere("m.to_user_id = $userId")
                    ->addWhere("m.readed = false")
                    ->fetchArray(true);
    }

}