<?php

/**
 * Messages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Message extends BaseMessage
{

    /**
     * Lookup for unreaded messages for a user
     * @param int $userId
     * @return array
     */
    public static function findUnreadByUserId($userId)
    {
        return Doctrine_Query::create()
                    ->from("Message m")
                    ->leftJoin("m.FromUser fu")
                    ->leftJoin("m.ToUser tu")
                    ->addWhere("m.to_user_id = $userId")
                    ->addWhere("m.readed = false")
                    ->fetchArray(true);
    }

    /**
     * Create a message to all admins
     * @param int $fromUser
     * @param string $subject
     * @param string $msg
     */
    public static function notifyAllAdmins($fromUser, $subject, $msg)
    {
        $admins = User::getAllAdmins();

        if (!empty($admins))
        {
            foreach($admins as $admin)
            {
                $message = new Message();
                $message->from_user_id = $fromUser;
                $message->to_user_id = $admin['id'];
                $message->subject = $subject;
                $message->content = $msg;
                $message->readed = false;
                $message->save();
            }
        }
    }

}