<?php

/**
 * Reservation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Reservation extends BaseReservation
{

    public static function findByUser($userId)
    {
        $now = date("Y-m-d G:i:s", time());

        return Doctrine_Query::create()
                    ->from("Reservation r")
                    ->leftJoin("r.User u")
                    ->leftJoin("r.Aircraft a")
                    ->leftJoin("r.ReservationStatus s")
                    ->leftJoin("s.ReservationType t")
                    ->addWhere("r.end_date > '$now'")
                    ->fetchArray(true);
    }

}