<?php

$data = array(
    "showEdit" => array(
        'controller' => "user",
        'action'     => "edit"
    ),
    'headerNames' => array(
        "Name", "Username", "Role", "Aircrafts"
    ),
    'showDelete' => array(
        'controller' => "user",
        'action'     => 'toggle',
        'message'    => "Are you sure to disable user?"
    ),
    'data' => $this->users,
    'columns' => array(
        array(
            'multi' => true,
            array(
                'name'      => 'first_name',
                'separator' => "&nbsp;"
            ),
            array(
                'name'  => "last_name",
                'separator' => "&nbsp;"
            ),
            array(
                "name" => "active",
                'container' => true,
                'check'     => true,
                'checkText' => "Disabled"
            )
        ),
        array("name" => "username"),
        array ('name' => array("AclRole", "name")),
        array (
            'helper' => 'showAircraft',
            'name'   => 'Aircraft'
        )
    )
);

echo $this->partial("partials/table.phtml", $data);

?>
<?php if($this->acl()->isValid('user', 'create')): ?>
    <?php $this->toolbar()
            ->addOnLoad()
            ->setButtonset(false)
            ->addButton("create-btn", $this->translate->_("Create user"), array('onclick' => "modalDialog('".$this->baseUrl."/user/create/format/json');"))?>
<?php endif; ?>
