<form method="post" action="<?= $this->url(array("login", "controller" => "user")) ?>">
    <fieldset>
        <legend><?= $this->translate->_("User login") ?></legend>
        <p>        
            <?= $this->formLabel("username", "Username:") ?>
            <?= $this->formText("username") ?>
        </p>
        <p>
            <?= $this->formLabel("password", "Password:") ?>
            <?= $this->formPassword("password") ?>
        </p>        
        <p>
            <?= $this->formSubmit("submit", "Login")?>
        </p>
    </fieldset>
</form>