<form method="post" action="<?= $this->url(array("login", "controller" => "user")) ?>">
    <fieldset>
        <legend><?= $this->translate->_("User login") ?></legend>
        <p>        
            <?= $this->formLabel("username", $this->translate->_("Username").":") ?>
            <?= $this->formText("username") ?>
        </p>
        <p>
            <?= $this->formLabel("password", $this->translate->_("Password").":") ?>
            <?= $this->formPassword("password") ?>
        </p>        
        <p>
            <?= $this->formSubmit("submit", $this->translate->_("Login"))?>
        </p>
    </fieldset>
</form>